import fs from "node:fs";

const elfFile = `${import.meta.dirname}/../../../pmb887x-emu/bsp/examples/apoxi_open_boot/build/app.elf`;
const binary = fs.readFileSync(elfFile);

fs.writeFileSync(
	`${import.meta.dirname}/../src/data/unlocker.elf.ts`,
	[
		`// DO NOT EDIT! AUTO-GENERATED BY tools/importApoxiUnlockerElf.ts`,
		`export default Buffer.from(\n\t${formatDataString(binary.toString("hex"))}, \n\t"hex"\n);`
	].join("\n") + "\n",
);

function formatDataString(data: string) {
	const chunks: string[] = [];
	for (let i = 0; i < data.length; i += 128) {
		chunks.push(`"${data.slice(i, i + 128)}"`);
	}
	return chunks.join(" + \n\t");
}
